name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - 'feature/**'
      - '001-a-playful-web'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Unit tests
        run: npm run test:unit

      - name: Integration tests
        run: npm run test:integration

      - name: Generate static build
        run: npm run generate

      - name: Performance budget check
        run: npm run analyze:bundle

      - name: Accessibility placeholder
        run: npm run test:accessibility
