name: Data Rotation & Site Refresh

on:
  schedule:
    # Data rotation: Run at 2 AM UTC daily
    #- cron: '0 2 * * *'

    # Site refresh: Every 15 minutes from 4 AM to 10 PM UTC (6 AM to midnight CET)
    #- cron: '*/15 4-22 * * *'

  workflow_dispatch: # Allow manual trigger

jobs:
  data-rotation:
    name: Rotate Old Data
    runs-on: ubuntu-latest
    # Only run at 2 AM, not on 15-min schedule
    if: github.event.schedule == '0 2 * * *' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Need full history for data files

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run data rotation script
        run: node scripts/rotate-data.mjs
        env:
          NODE_ENV: production

      - name: Commit rotated data
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add src/server/data/sentiment/daily-*.json
          git diff --staged --quiet || git commit -m "chore: rotate hourly data to daily aggregates [skip ci]"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

  sentiment-fetch:
    name: Fetch Sentiment Data
    runs-on: ubuntu-latest
    # Run on 15-min schedule or manual trigger, but NOT on data rotation schedule
    if: github.event.schedule == '*/15 4-22 * * *' || (github.event_name == 'workflow_dispatch' && github.event.inputs.refresh_only == 'true')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Fetch sentiment from live sources
        run: node scripts/fetch-sentiment.mjs
        env:
          SITE_URL: https://zorg-sentiment.netlify.app

      - name: Wait for data processing
        run: sleep 10

  netlify-refresh:
    name: Trigger Netlify Build
    runs-on: ubuntu-latest
    needs: [sentiment-fetch]
    # Run on 15-min schedule or manual trigger, but NOT on data rotation schedule
    if: github.event.schedule == '*/15 4-22 * * *' || (github.event_name == 'workflow_dispatch' && github.event.inputs.refresh_only == 'true')

    steps:
      - name: Trigger Netlify Deploy Hook
        env:
          NETLIFY_BUILD_HOOK_URL: ${{ secrets.NETLIFY_BUILD_HOOK_URL }}
        run: |
          if [ -z "$NETLIFY_BUILD_HOOK_URL" ]; then
            echo "❌ NETLIFY_BUILD_HOOK_URL secret is not set."
            echo "   Set repository secret NETLIFY_BUILD_HOOK_URL with your Netlify build hook."
            echo "   Get it from: Netlify dashboard → Site settings → Build & deploy → Build hooks"
            exit 1
          fi
          curl -Ssf -X POST -d '{}' "$NETLIFY_BUILD_HOOK_URL"
          echo "✅ Netlify build hook triggered"

      - name: Log refresh
        run: |
          echo "✅ Netlify build triggered at $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
          echo "   Active hours: 6 AM - midnight CET"
          echo "   Refresh cadence: 15 minutes"

  manual-trigger:
    name: Manual Trigger (Both Jobs)
    runs-on: ubuntu-latest
    # Only run when manually triggered without refresh_only flag
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.refresh_only != 'true'

    steps:
      - name: Run data rotation
        uses: ./.github/workflows/data-rotation.yml@main

      - name: Trigger site refresh
        env:
          NETLIFY_BUILD_HOOK_URL: ${{ secrets.NETLIFY_BUILD_HOOK_URL }}
        run: |
          if [ -z "$NETLIFY_BUILD_HOOK_URL" ]; then
            echo "❌ NETLIFY_BUILD_HOOK_URL secret is not set."
            echo "   Set repository secret NETLIFY_BUILD_HOOK_URL with your Netlify build hook."
            echo "   Get it from: Netlify dashboard → Site settings → Build & deploy → Build hooks"
            exit 1
          fi
          curl -Ssf -X POST -d '{}' "$NETLIFY_BUILD_HOOK_URL"
          echo "✅ Both data rotation and site refresh triggered"
